language: android
jdk: oraclejdk8
android:
  components:
    # Install latest SDK and tools
    - platform-tools
    - tools

    # The BuildTools version
    - build-tools-25.0.0

    # The SDK version used to compile
    - android-22

    # Use extra android repo locations to find the appcompat-v7:21.0.0 support library
    - extra

# Specify the build script to run.
script: "./travis/build.sh"
